### ISSUE TITLE
There are service offerings not allowed for VM starting in VM creation

### ISSUE THREAD

**Issue by qqcky** [bwsw/cloudstack-ui#917] opened 2018-01-25 02:34 UTC
**Steps to reproduce:**
1. Go to VM creation
2. Choose `customServiceOffering1`
3. Create and try to start this VM

**Expected result:** VM created and started successfully
**Actual result:** VM created (if start option in VM creation = `false`), but cannot be started with an error ('Unable to create a deployment for VM[User|i-4-1131-VM]')

**Connected feature:** 
- vm_start
- vm_SO_change
- vm_deploy
- vm_creation_so_custom

![Снимок экрана от 2018-01-25 09-33-08.png](https://images.zenhubusercontent.com/5971bcd561b4ca3b0a7537c1/30ac272c-a685-4ec5-8315-307849d2799f)

**Comment by bwsw** [comment] 2018-01-26 05:14
@Nadya913 @ershovaelena @qqcky 
This service offering is completely incompatible with the deployment because it assumes hosts have GPU Nvidia Grid K1. Not a bug. Don't create dumb, trashy service offering, please.

**Comment by ershovaelena** [comment] 2018-01-26 05:59
Discussed with PO: out of scope to manage potentially broken SOs.

**Closed by ershovaelena** 2018-01-26 05:59 UTC
Labels: bug, statistics bug: regression
