### ISSUE TITLE
Ability to add a Firewall rule when incorrect ICMP type/code for IPv6

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#998] opened 2018-02-19 11:19 UTC
There is ability to add a rule with ICMP type/code (-1, -1) when IPv6

Steps:
1. Go to Firewall rules editing
2. Select ICMP protocol
3. Fill "CIDR v4/v6" by IPv6 and  "ICMP type/code" by (-1, -1) (right after refresh)

Expected result: ICMP type/code are invalid, add-button is disabled
Actual result: ICMP type/code are valid, add-button is enabled, when click add-button - rule is added successfully

![v6-1-1](https://user-images.githubusercontent.com/32011943/36375101-85f1e4fe-15a0-11e8-85e7-8077b9c50ea4.png)

**Connected Feature ID:** 
_firewall_rules_edit
vm_firewall_rules_edit_

**Comment by tamazlykar** [comment] 2018-03-28 02:07
**Test on**
tamazlykar/998-firewall-icmp

**Regression:**
firewall_rules_edit
vm_firewall_rules_edit

**Comment by tamazlykar** [comment] 2018-03-28 04:56
@Nadya913 This is not a bug. 
@bwsw explained that Cloudstack interpret -1 as any value
https://cwiki.apache.org/confluence/display/CLOUDSTACK/Routing+between+Guest+networks

**Comment by tamazlykar** [comment] 2018-05-08 08:12
I misunderstood this issue. There is an error. -1 value is incorrect for IP v6 and correct for v4!
But this should be fixed #1019

**Comment by chewlite** [comment] 2018-05-10 02:07
@tamazlykar 

Tested on:
tamazlykar/1019-firewall-rules

**Closed** 2018-05-11 03:29 UTC
Labels: bug, severity: major, statistics bug: regression
