### ISSUE TITLE
Checkbox 'Show system tags' isn't active by default in Tag tab

### ISSUE THREAD

**Issue by evgeniiamokhova** [bwsw/cloudstack-ui#1542] opened 2019-01-29 03:47 UTC
If new user is created checkbox 'Show system tags' isn't active by default in Tag tab.

### Steps to reproduce
1) Login by new created  user
2) Open sidebar of VM
3) Go to Tags

### Actual result
Checkbox 'Show system tags' isn't active by default in Tag tab.

### Expected result
Checkbox is active by default according to REQ_VM_DTLS_034

### Environment
<pre><code>
Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] Safari version XX
- [x] Opera version XX
- [x] IE version XX
- [x] Edge version XX
</code></pre>

### Connected requirement IDs
[REQ_VM_DTLS_034]

### Screenshots
![2019-01-29 09-14-51](https://user-images.githubusercontent.com/45107015/51883374-382c7080-23b5-11e9-915e-3a6b1bc167c2.png)

**Comment by ershovaelena** [comment] 2019-01-30 02:47
@evgeniiamokhova @Nadya913 @nikonov1996 This is not a bug. There was a mistake in requirement  REQ_VM_DTLS_034 (system tags must be hidden by default). Description fixed now.

**Closed by ershovaelena** 2019-01-30 02:47 UTC
Labels: bug, severity: major, statistics bug: regression
