### ISSUE TITLE
Invalid VM is created even error appears for For CPU (Mhz) more than 3000 Mhz

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#916] opened 2018-01-25 02:21 UTC
Url: http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/instances/create
User: Develop
For CPU (Mhz) more than 3000 Mhz in creating VM with custom service offering, Error is shown but empty VM is created.

Steps:
1. Log in, go to VM and press Add;
2. Select Custom service offering;
3. Set CPU (Mhz) value more 3000 and press "Confirm"; 
4. Press Create;

Actual rezult: Error occurs, empty VM is created.
Expected rezult: Field CPU (Mhz) does not allow entering more than the maximum allowed value. When creating a VM, an error is shown and no VM is created;

Connected feature ID: vm_deploy, vm_creation_so_custom.
Screenshot:
![Mhz Create 2.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/82955b93-2b69-4541-892e-b96e6b875cd7)
![Mhz Create 3.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/4cf79f34-06eb-463d-829a-6764866bb7e8)

**Comment by ershovaelena** [comment] 2018-01-25 09:04
Seems to be the same problem as in #917. Check 917 and if this one is solved there - close this ticket.

**Comment by bwsw** [comment] 2018-01-26 05:08
@ershovaelena @rennervo @Nadya913 

Not a bug. No CPU available with freq 3000 for the deployment. Might be useful to add per certain custom offering MHz limit to config.

**Closed** 2018-01-26 05:59 UTC
Labels: bug, severity: major, statistics bug: regression
