### ISSUE TITLE
Domain Admin has an ability to delete his own Account

### ISSUE THREAD

**Issue by chewlite** [bwsw/cloudstack-ui#1020] opened 2018-03-07 07:29 UTC
Steps:

1. Create a user in account with role Domain Admin
2. Log in under that new user and go to Accounts

Expected result: no actionbox in the card/sidebar of his own account
Actual result: actionbox in the card/sidebar of his own account where all actions are enabled

**Connected Feature ID:**
account_actionbox

**Comment by tamazlykar** [comment] 2018-03-23 07:10
Unable to reproduce bug
@Nadya913

**Comment by tamazlykar** [comment] 2018-04-11 02:47
@Nadya913  Issue was closed by mistake and branch was merged so you can test it on the master branch

**Comment by chewlite** [comment] 2018-04-11 05:33
There is actionbox in the sidebar of new user Account where all actions are enabled

**Comment by tamazlykar** [comment] 2018-04-19 01:52
@Nadya913 test it on the master branch

**Comment by rennervo** [comment] 2018-04-19 06:47
Tested on master

**Closed** 2018-04-19 07:37 UTC
Labels: bug, severity: critical, statistics bug: regression
