### ISSUE TITLE
The number of free resources is not updated after committing actions to change resources

### ISSUE THREAD

**Issue by rennervo** [bwsw/cloudstack-ui#1340] opened 2018-10-16 04:50 UTC
### Description
The system does not set limits on resources since the number of free resources is not updated automatically after committing actions that change the number of resources.
You must automatically update the number of free resources for the following actions:
- Create VM
- Change Root disk size in VM sidebar
- Change Additional disk size in VM sidebar
- Change Service Offering in VM sidebar
- Delete VM
- Create Additional storage in VM sidebar
- Create Additional storage in the Storage section
- Change Additional disk size in the Storage section
- Delete Additional storage in VM sidebar
- Delete Additional storage in the Storage section 
- Revert to snapshot (in VM sidebar, in the Storage section, in the Snapshot section)
- Create a volume from a snapshot (in VM sidebar, in the Storage section, in the Snapshot section)
- Delete volumes when VM deleting

### Steps to reproduce
1. Log in as admin
2. Create a new Account with "User" role and limits (8 CPU, 2048 Memory, 100 Primary storage)
3. Logout and login as the new user
4. Go to create VM
5. Set Custom SO to 8 CPU, 2048 Memory
6. Set Root disk size to 100 GB
7. Fill in the remaining required fields and create a VM
8. Go to create VM

### Actual result
- The window for creating a VM opens
- You can choose the size of the root disk from the size of the template to 100 GB
- In SO, you can set the CPU value from 1 to 8, the memory from 512 to 2048
- In no case does a resource limit error occur
- You can send a request to create a VM (an error will be received during deployment, see screenshots)

### Expected result
Instead of the VM creation window, an error about insufficient resources is shown.

### Environment

<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX
Others:
</code></pre>

### Connected feature ID

vm_creation_so
vm_creation_so_custom
vm_creation_rootdisk_resize
vm_creation_diskoffering_resize
vm_disk_resize
vm_disk_attached_delete
vm_disk_attach_new
vm_SO_change
vm_expunge
vm_vmsnap_reverttosnap
vm_disk_snap_volume_create
vm_destroy_datadrives
storage_disk_resize
storage_disk_delete
storage_snap_volume_create
storage_snap_reverttosnap
storage_disk_create
volsnapshot_volume_create
volsnapshot_reverttosnap

### Screenshots
![update resource 1.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/b43410c2-ddc3-4748-b0ee-d8a33a945846)
![update resource 2.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/38b7c1f3-6a2d-4966-897b-91a05ebbd007)
![update resource 3.png](https://images.zenhubusercontent.com/5a5c77c24b5806bc2bc2be22/71304044-8cc1-4263-8f08-a92311796842)

**Comment by Nadya913** [comment] 2018-10-24 10:11
According https://github.com/bwsw/cloudstack-ui/issues/1242#issuecomment-430100375 here it should be fixed but not.
No Storage resources but create button is enabled and no message about exceeded resources.

![overstorage](https://user-images.githubusercontent.com/33111683/47423504-5fb8df00-d7af-11e8-81af-924ece7f9623.png)
Expected: Create button is disabled, Disk Size  is 0, message "The disk offering cannot be selected because it doesn't fit the account resources available." is shown in list and in vm creation dialog.
Actual: Create button is enabled, Disk Size  is 10, error got if tru to create VM
Maximum amount of resources of Type = 'primary_storage' for Account Name = Limit in Domain Id = 2 is exceeded: Account Resource Limit = 16106127360, Current Account Resource Amount = 16106127360, Requested Resource Amount = 10737418240.

**Comment by Nadya913** [comment] 2018-10-25 04:54
For testing all mentioned features need to be 1242 will be closed.

**Comment by Nadya913** [comment] 2018-11-09 04:45
Lack 2:
1. Error message appears in VM creation in case if resourses is enough.

Steps:

- Login by user
-  Create few disks to exceeded limit for primary storage
-  Delete any disk (more than 10 gb)
-  Create new VM and choose ISO for installation source
Expected: no message appears, create buttom is available
Actual: error message appears, create button is disabled
![limit](https://user-images.githubusercontent.com/33111683/48243831-0094d480-e415-11e8-858a-33f4d48a8123.png)

**Comment by ershovaelena** [comment] 2018-11-26 03:09
@Nadya913 please provide additional cases: ISO, templates, snapshots. This issue should be completed.

**Comment by Nadya913** [comment] 2018-11-26 08:12
Statistics don't updated for cases: 
Primary storage - Revert to snapshot (in VM sidebar, in the Storage section, in the Snapshot section)

**Comment by ershovaelena** [comment] 2018-11-27 07:16
@wowshakhov please, check the following cases:
- VM creation
- Revert to snapshot (in VM sidebar, in the Storage section, in the Snapshot section)
- Create a volume from a snapshot (in VM sidebar, in the Storage section, in the Snapshot section)

And send the issue to code review

Other cases will be tested during regression testing by QA

**Comment by ershovaelena** [comment] 2018-11-28 06:47
Regression:
REQ_VM_DTLS_016, REQ_VM_DTLS_017
REQ_STORAGE_DTLS_008, REQ_STORAGE_DTLS_009
REQ_SNAP_LIST_008

**Comment by rennervo** [comment] 2018-11-29 07:37
Tested on 1406

**Closed** 2018-11-29 08:03 UTC
Labels: bug, severity: major, statistics bug: regression
