### ISSUE TITLE
All actions for not backed up snaphot are shown in VM sidebar, no icon for Create Template action

### ISSUE THREAD

**Issue by Nadya913** [bwsw/cloudstack-ui#990] opened 2018-02-15 10:54 UTC
All actions are available for snapshot with error, allocated,  status. Action for Create Template has no icon for snapshot with Backed Up status. 

Steps:
1. Login and go to VM
2. Attach data disk to this VM
3. Create few snapshots - one by one
4. Go to VM sidebar/Storage and see actions 
5. Open View All

Actual result: 
1. All actions are available for not backed up snapshot. 
2. Action for Create Template has no icon for snapshot with Backed Up status. 

Expected result: 
1. Only Delete action are available for not backed up snapshot. 
2. Action for Create Template has icon for snapshot with Backed Up status. 
![actions.png](https://images.zenhubusercontent.com/59faba338a75884b9085bd93/fe451f3d-ad41-49ef-ad2e-cd61d07dfc4a)

**Comment by ershovaelena** [comment] 2018-03-28 02:38
@tamazlykar no feature ID provided. Please, check out features involved in this issue.

**Comment by tamazlykar** [comment] 2018-03-30 06:46
Feature ID:
vm_disk_snap_display

**Comment by tamazlykar** [comment] 2018-03-30 08:58
Also there is no tool-tip assigned to this actions. Need to fix

**Comment by ershovaelena** [comment] 2018-04-03 06:57
TBD in #1049

**Comment by tamazlykar** [comment] 2018-05-22 02:55
@Nadya913 please check whether the problem is solved on the master branch.

**Comment by ershovaelena** [comment] 2018-05-23 04:42
@tamazlykar please fix 2nd problem (1st was fixed in #1049)

**Comment by rennervo** [comment] 2018-06-09 05:55
Tested on tamazlykar/990-snapshot-actions/

**Closed** 2018-06-14 05:53 UTC
Labels: bug, severity: critical, statistics bug: regression
